### PR TITLE
Safari sliderbug

### PR DESCRIPTION
**Pull request by gduck**
safari was allowing you to scroll left past the starcluster even with overflow:hidden. 
changing starcluster to position:fixed... well.. fixed it

### CODE REVIEW

**Comment by gduck** [comment]
Actually - yes, you are right. 
- Quick fix #1 - make the stars pos:fixed also, and they will stay together as page scrolls vertically
- Not as quick fix #2 - fiddle with the containers & positioning to make it act as now
I can add #1 now as it removes the horizontal scroll bug & look into doing #2

**Comment by gduck** [comment]
What #1 looks like

stars_fixed_position

**Comment by tijptjik** [comment]
well, I'd prefer it if Droste moved the satellites and stars of this universe, but I understand they move for no-one :) Let's merge it in and see how it hold up across platforms!

**Comment by tijptjik** [comment]
This actually causes performance / rendering issues for some browsers (`Chrome `on Android, `IE11` and `Edge` on Windows). So ideally there would be another way to presvent the sides from blowing out without fixing it.

**Pull request merged**
